#!/usr/bin/env python3
"""
Compliance Matrix Generator
Generates a compliance impact matrix from CWE findings.

Usage:
    cat findings.json | python generate-matrix.py > compliance-matrix.md
    python generate-matrix.py < findings.json

Input JSON format:
[
  {"cwe_id": 89, "name": "SQL Injection", "severity": "CRITICAL", "count": 2},
  {"cwe_id": 502, "name": "Deserialization", "severity": "HIGH", "count": 1}
]

Output: Markdown table showing regulatory impact
"""

import argparse
import io
import json
import os
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


# Hard-coded framework versions — single source of truth, bumped when the skill
# version bumps. Audits emitted by this version certify against THESE framework
# versions and no others. See CHANGELOG.md for what changes when bumping.
FRAMEWORK_VERSIONS = (
    "CWE List 4.16 (2024-11), "
    "OWASP Top 10:2021, "
    "OWASP LLM Top 10 v1.1 (2024-10), "
    "NIST SP 800-53 Rev. 5 (2020-09 + 5.1.1 2023-12), "
    "EU AI Act Arts. 15/35/37 (Reg. (EU) 2024/1689), "
    "ISO/IEC 27001:2022, "
    "SOC 2 (AICPA TSC 2017+2022), "
    "MITRE ATT&CK v17.1 (2025-04), "
    "MITRE ATLAS v4.7.0 (2025-01)"
)
SOURCES_CURRENT_AS_OF_DEFAULT = "2026-05"
CHANGELOG_URL = "https://github.com/justice8096/cwe-mapper/blob/master/CHANGELOG.md"


def _git(args: list, cwd: Optional[str] = None) -> Optional[str]:
    """Run a git command and return stripped stdout, or None on failure."""
    try:
        result = subprocess.run(
            ["git"] + args, cwd=cwd, capture_output=True, text=True,
            check=False, timeout=5,
        )
        if result.returncode == 0:
            return result.stdout.strip() or None
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        pass
    return None


def _detect_skill_version() -> str:
    script_dir = Path(__file__).resolve().parent
    for parent in [script_dir.parent.parent.parent, script_dir.parent.parent, script_dir.parent]:
        plugin_json = parent / ".claude-plugin" / "plugin.json"
        if plugin_json.exists():
            try:
                with open(plugin_json, encoding="utf-8") as f:
                    return json.load(f).get("version", "unknown")
            except (json.JSONDecodeError, OSError):
                continue
    return "unknown"


def _detect_skill_commit() -> str:
    return _git(["rev-parse", "--short", "HEAD"], cwd=str(Path(__file__).resolve().parent)) or "unknown"


def _detect_target_repo(cwd: str) -> str:
    url = _git(["config", "--get", "remote.origin.url"], cwd=cwd)
    if url:
        name = url.rstrip("/").rsplit("/", 1)[-1]
        if name.endswith(".git"):
            name = name[:-4]
        return name
    return Path(cwd).name


def _detect_target_commit(cwd: str) -> str:
    return _git(["rev-parse", "--short", "HEAD"], cwd=cwd) or "unknown"


def _detect_target_branch(cwd: str) -> str:
    return _git(["rev-parse", "--abbrev-ref", "HEAD"], cwd=cwd) or "unknown"


def _provenance_block(
    skill_version: str, skill_commit: str,
    target_repo: str, target_commit: str, target_branch: str,
    sources_current_as_of: str,
) -> str:
    """Required Provenance Block per the Skill Versioning and Addendum Framework."""
    timestamp = datetime.now(timezone.utc).isoformat()
    lines = ["## Provenance Block", ""]
    lines.append(f"- **Generated**: {timestamp}")
    lines.append(f"- **Generated by**: cwe-mapper v{skill_version} (`{skill_commit}`)")
    lines.append(
        f"- **Target project**: {target_repo} @ `{target_commit}` "
        f"on branch `{target_branch}`"
    )
    lines.append(
        f"- **Sources current as of**: {sources_current_as_of} "
        f"(except where individual findings note otherwise)"
    )
    lines.append(f"- **Framework versions**: {FRAMEWORK_VERSIONS}")
    lines.append(f"- **Skill changelog**: {CHANGELOG_URL}")
    return "\n".join(lines)

CWE_MAPPINGS = {
    20: {
        'name': 'Improper Input Validation',
        'owasp_2021': ['A03'],
        'nist': ['SI-10', 'CM-6'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.1'],
        'soc2': ['CC2', 'CC6'],
    },
    22: {
        'name': 'Path Traversal',
        'owasp_2021': ['A01'],
        'nist': ['AC-3'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.3'],
        'soc2': ['CC2', 'CC5'],
    },
    78: {
        'name': 'OS Command Injection',
        'owasp_2021': ['A03'],
        'nist': ['SI-10'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.1'],
        'soc2': ['CC6'],
    },
    79: {
        'name': 'Cross-site Scripting (XSS)',
        'owasp_2021': ['A03'],
        'nist': ['SI-10'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.1'],
        'soc2': ['CC6'],
    },
    89: {
        'name': 'SQL Injection',
        'owasp_2021': ['A03'],
        'nist': ['SI-10', 'CM-6'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.1'],
        'soc2': ['CC6'],
    },
    94: {
        'name': 'Code Injection',
        'owasp_2021': ['A03'],
        'nist': ['SI-10'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.1'],
        'soc2': ['CC6'],
    },
    287: {
        'name': 'Improper Authentication',
        'owasp_2021': ['A07'],
        'nist': ['IA-2', 'IA-5'],
        'eu_ai_act': ['Article 35'],
        'iso_27001': ['A9.2'],
        'soc2': ['CC6'],
    },
    306: {
        'name': 'Missing Authentication for Critical Function',
        'owasp_2021': ['A01'],
        'nist': ['AC-2'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.3'],
        'soc2': ['CC6'],
    },
    327: {
        'name': 'Broken Cryptography',
        'owasp_2021': ['A02', 'A05'],
        'nist': ['SC-13'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.13'],
        'soc2': ['CC9'],
    },
    352: {
        'name': 'Cross-Site Request Forgery',
        'owasp_2021': ['A01'],
        'nist': ['SI-10'],
        'eu_ai_act': [],
        'iso_27001': [],
        'soc2': [],
    },
    434: {
        'name': 'Unrestricted File Upload',
        'owasp_2021': ['A04'],
        'nist': ['CM-3', 'SI-10'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.5'],
        'soc2': ['CC5'],
    },
    502: {
        'name': 'Unsafe Deserialization',
        'owasp_2021': ['A08'],
        'nist': ['SI-7', 'SI-10'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.1'],
        'soc2': ['PI1', 'CC6'],
    },
    611: {
        'name': 'XML External Entity (XXE)',
        'owasp_2021': ['A05', 'A08'],
        'nist': ['SI-10'],
        'eu_ai_act': ['Article 35'],
        'iso_27001': [],
        'soc2': [],
    },
    798: {
        'name': 'Hard-coded Credentials',
        'owasp_2021': ['A05'],
        'nist': ['IA-5'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.4'],
        'soc2': ['CC6'],
    },
    862: {
        'name': 'Missing Authorization',
        'owasp_2021': ['A01'],
        'nist': ['AC-6', 'AC-2'],
        'eu_ai_act': ['Article 35'],
        'iso_27001': ['A8.3'],
        'soc2': ['CC6'],
    },
    918: {
        'name': 'Server-Side Request Forgery (SSRF)',
        'owasp_2021': ['A10'],
        'nist': ['SC-7'],
        'eu_ai_act': ['Article 15'],
        'iso_27001': ['A8.1'],
        'soc2': ['CC6'],
    },
}


def generate_matrix(
    findings: list,
    skill_version: Optional[str] = None,
    skill_commit: Optional[str] = None,
    target_repo: Optional[str] = None,
    target_commit: Optional[str] = None,
    target_branch: Optional[str] = None,
    sources_current_as_of: Optional[str] = None,
) -> str:
    """Generate compliance matrix markdown.

    Emits a Provenance Block at the top per the Skill Versioning and Addendum
    Framework. All provenance fields auto-detect from git/plugin.json when not
    provided. cwe-mapper outputs feed the entire security audit pipeline, so
    reproducibility is critical — every report must be traceable to a specific
    skill version + commit + framework-version snapshot.
    """
    cwd = os.getcwd()
    output = []
    output.append('# Security Findings Compliance Impact Matrix\n')
    output.append('')
    output.append(_provenance_block(
        skill_version=skill_version or _detect_skill_version(),
        skill_commit=skill_commit or _detect_skill_commit(),
        target_repo=target_repo or _detect_target_repo(cwd),
        target_commit=target_commit or _detect_target_commit(cwd),
        target_branch=target_branch or _detect_target_branch(cwd),
        sources_current_as_of=sources_current_as_of or SOURCES_CURRENT_AS_OF_DEFAULT,
    ))
    output.append('\n')
    output.append(f'**Findings analyzed**: {len(findings)}\n')

    # Summary by severity
    severity_counts = defaultdict(int)
    owasp_items = set()
    nist_controls = set()
    eu_ai_articles = set()
    iso_controls = set()
    soc2_criteria = set()

    for finding in findings:
        cwe_id = finding.get('cwe_id')
        severity = finding.get('severity', 'UNKNOWN')
        count = finding.get('count', 1)

        if cwe_id in CWE_MAPPINGS:
            severity_counts[severity] += count
            mapping = CWE_MAPPINGS[cwe_id]

            owasp_items.update(mapping.get('owasp_2021', []))
            nist_controls.update(mapping.get('nist', []))
            eu_ai_articles.update(mapping.get('eu_ai_act', []))
            iso_controls.update(mapping.get('iso_27001', []))
            soc2_criteria.update(mapping.get('soc2', []))

    output.append('## Summary\n')
    output.append('| Severity | Count |\n')
    output.append('|----------|-------|\n')
    for severity in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']:
        count = severity_counts.get(severity, 0)
        if count > 0:
            output.append(f'| {severity} | {count} |\n')

    # Framework impact
    output.append('\n## Regulatory Framework Impact\n')
    output.append(f'- **OWASP Top 10 2021**: {len(owasp_items)} categories affected\n')
    output.append(f'- **NIST SP 800-53**: {len(nist_controls)} controls affected\n')
    output.append(f'- **EU AI Act**: {len(eu_ai_articles)} articles affected\n')
    output.append(f'- **ISO 27001**: {len(iso_controls)} controls affected\n')
    output.append(f'- **SOC 2**: {len(soc2_criteria)} criteria affected\n')

    # Detailed findings
    output.append('\n## Findings by CWE\n')
    for finding in sorted(findings, key=lambda x: x.get('cwe_id', 0)):
        cwe_id = finding.get('cwe_id')
        if cwe_id not in CWE_MAPPINGS:
            continue

        mapping = CWE_MAPPINGS[cwe_id]
        name = mapping['name']
        severity = finding.get('severity', 'UNKNOWN')
        count = finding.get('count', 1)

        output.append(f'\n### CWE-{cwe_id}: {name}\n')
        output.append(f'**Severity**: {severity} | **Instances**: {count}\n\n')

        output.append('**Regulatory Mapping**:\n')
        output.append('| Framework | Controls/Items |\n')
        output.append('|-----------|----------------|\n')

        if mapping.get('owasp_2021'):
            output.append(f"| OWASP 2021 | {', '.join(mapping['owasp_2021'])} |\n")
        if mapping.get('nist'):
            output.append(f"| NIST 800-53 | {', '.join(mapping['nist'])} |\n")
        if mapping.get('eu_ai_act'):
            output.append(f"| EU AI Act | {', '.join(mapping['eu_ai_act'])} |\n")
        if mapping.get('iso_27001'):
            output.append(f"| ISO 27001 | {', '.join(mapping['iso_27001'])} |\n")
        if mapping.get('soc2'):
            output.append(f"| SOC 2 | {', '.join(mapping['soc2'])} |\n")

    # Cross-framework summary
    output.append('\n## Framework Compliance Checklist\n')
    output.append('\n### OWASP Top 10 2021\n')
    output.append('| Item | Affected | Controls |\n')
    output.append('|------|----------|----------|\n')
    for item in sorted(owasp_items):
        output.append(f'| {item} | YES | See findings above |\n')

    output.append('\n### NIST SP 800-53 Controls\n')
    output.append('| Control | Affected | Findings |\n')
    output.append('|---------|----------|----------|\n')
    for control in sorted(nist_controls):
        output.append(f'| {control} | YES | See findings above |\n')

    output.append('\n### EU AI Act Articles\n')
    output.append('| Article | Requirement | Status |\n')
    output.append('|---------|-------------|--------|\n')
    for article in sorted(eu_ai_articles):
        output.append(f'| {article} | Risk Assessment/Documentation | **NON-COMPLIANT** |\n')

    output.append('\n### ISO 27001 Controls\n')
    output.append('| Control | Category | Status |\n')
    output.append('|---------|----------|--------|\n')
    for control in sorted(iso_controls):
        output.append(f'| {control} | Technological | **REQUIRES REMEDIATION** |\n')

    output.append('\n### SOC 2 Criteria\n')
    output.append('| Criteria | Definition | Status |\n')
    output.append('|----------|------------|--------|\n')
    for criteria in sorted(soc2_criteria):
        output.append(f'| {criteria} | See SOC 2 definition | **AT RISK** |\n')

    # Remediation priority
    output.append('\n## Remediation Priority\n')
    output.append('\n1. **Critical CWEs** (Fix Immediately)\n')
    for finding in findings:
        if finding.get('severity') == 'CRITICAL':
            cwe_id = finding.get('cwe_id')
            if cwe_id in CWE_MAPPINGS:
                output.append(f"   - CWE-{cwe_id}: {CWE_MAPPINGS[cwe_id]['name']}\n")

    output.append('\n2. **High CWEs** (Fix This Sprint)\n')
    for finding in findings:
        if finding.get('severity') == 'HIGH':
            cwe_id = finding.get('cwe_id')
            if cwe_id in CWE_MAPPINGS:
                output.append(f"   - CWE-{cwe_id}: {CWE_MAPPINGS[cwe_id]['name']}\n")

    output.append('\n3. **Medium CWEs** (Plan Next Sprint)\n')
    for finding in findings:
        if finding.get('severity') == 'MEDIUM':
            cwe_id = finding.get('cwe_id')
            if cwe_id in CWE_MAPPINGS:
                output.append(f"   - CWE-{cwe_id}: {CWE_MAPPINGS[cwe_id]['name']}\n")

    return ''.join(output)


def main():
    """Main entry point.

    Emits a Provenance Block at the top of the compliance matrix per the Skill
    Versioning and Addendum Framework — required for legal-grade audit
    reproducibility. All provenance fields auto-detect from git/plugin.json
    unless overridden via CLI flags.
    """
    parser = argparse.ArgumentParser(
        description="Generate a compliance impact matrix from CWE findings. "
        "Reads findings JSON from stdin, writes matrix markdown to stdout. "
        "Emits a Provenance Block at the top of every matrix per the Skill "
        "Versioning and Addendum Framework."
    )
    # Provenance overrides — optional, auto-detected from git/plugin.json.
    parser.add_argument("--skill-version", help="Override detected skill version")
    parser.add_argument("--skill-commit", help="Override detected skill commit")
    parser.add_argument("--target-repo", help="Target project repo name (default: cwd git remote/basename)")
    parser.add_argument("--target-commit", help="Target project commit (default: cwd git short HEAD)")
    parser.add_argument("--target-branch", help="Target project branch (default: cwd git current branch)")
    parser.add_argument(
        "--sources-current-as-of",
        help="Override sources-current-as-of (YYYY-MM); default: " + SOURCES_CURRENT_AS_OF_DEFAULT
    )
    args = parser.parse_args()

    # CWE-755: Proper error handling — errors to stderr with exit codes
    MAX_INPUT_BYTES = 10 * 1024 * 1024  # 10 MB
    try:
        # Read raw bytes from stdin and decode as utf-8; the prior implementation
        # used sys.stdin.read() which respects the locale encoding and breaks on
        # non-utf-8 Windows shells.
        raw_input = sys.stdin.buffer.read(MAX_INPUT_BYTES).decode('utf-8', errors='replace')
        if len(raw_input.encode('utf-8')) == MAX_INPUT_BYTES:
            print("Error: Input exceeds 10 MB maximum", file=sys.stderr)
            sys.exit(1)
        if not raw_input.strip():
            print('Error: Empty input', file=sys.stderr)
            sys.exit(1)
        findings = json.loads(raw_input)
    except json.JSONDecodeError as e:
        print(f'Error: Invalid JSON input - {e}', file=sys.stderr)
        sys.exit(1)

    if not isinstance(findings, list):
        print('Error: Input must be a JSON array', file=sys.stderr)
        sys.exit(1)

    # CWE-20: Validate finding structure
    for i, finding in enumerate(findings):
        if not isinstance(finding, dict):
            print(f'Error: Finding at index {i} must be a JSON object', file=sys.stderr)
            sys.exit(1)
        cwe_id = finding.get('cwe_id')
        if cwe_id is not None:
            try:
                int(cwe_id)
            except (TypeError, ValueError):
                print(f'Error: Invalid cwe_id at index {i}', file=sys.stderr)
                sys.exit(1)

    matrix = generate_matrix(
        findings,
        skill_version=args.skill_version,
        skill_commit=args.skill_commit,
        target_repo=args.target_repo,
        target_commit=args.target_commit,
        target_branch=args.target_branch,
        sources_current_as_of=args.sources_current_as_of,
    )

    # Force utf-8 stdout to handle em-dashes and other non-ASCII in the Provenance
    # Block. Without this, Python on Windows defaults to cp1252 and raises
    # UnicodeEncodeError when the matrix is printed.
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', newline='\n', write_through=True)
    print(matrix)


if __name__ == '__main__':
    main()
